#!/bin/sh
#Downloads and runs build-gnuradio
prefix=/usr/local
bmag='\033[0;45m'
nc='\033[0m'

echo -e "${bmag}Welcome. Lets install Gnuradio using PyBOMBS.${nc}"

echo -e "${bmag}Making sure we're up to date${nc}"
sudo apt update
echo -e "${bmag}Installing latest tools${nc}"
sudo apt install python-pip python-apt git -y
echo -e "${bmag}Updating pip...${nc}"
sudo -H pip install --upgrade pip
echo -e "${bmag}Installing PyBOMBS from GitHub${nc}"
sudo -H pip install --upgrade git+https://github.com/gnuradio/pybombs.git
echo -e "${bmag}Adding recipes:${nc}"
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
echo -e "${bmag}Setup, build, and install. Using $prefix ${nc}"
sudo pybombs prefix init $prefix -a myprefix -R gnuradio-default
sudo pybombs install fftw rtl-sdr gr-osmosdr
sudo ldconfig

echo -e "${bmag}Setup User Icons${nc}"

sudo chmod 755 $prefix/libexec/gnuradio/grc_setup_freedesktop
sudo $prefix/libexec/gnuradio/grc_setup_freedesktop install

echo -e "${bmag}Done building gnuradio. Updating .bashrc${nc}"
PPCHECK="export PYTHONPATH=/usr/local/lib/python2.7/dist-packages"
#add the rest of the python path

if grep -q "$PPCHECK" ~/.bashrc
then echo "Python path is up to date in ~/.bashrc"
else echo $PPCHECK >> ~/.bashrc
fi

echo -e "${bmag}Adding black lists${nc}"
#sudo touch /etc/modprobe.d/no-rtl.conf
blc=no-rtl.conf
if [ -e "/etc/modprobe.d/$blc" ] ; then

cat > $blc  << EOF
blacklist dvb_usb_rtl28xxu
blacklist rtl2832
blacklist rtl2830
EOF

	sudo cp ./$blc /etc/modprobe.d/
	rm $blc
else 
	echo -e "${bmag}$blc Exists in /etc/modprobe.d/, not creating${nc}"
fi

echo -n -e "${bmag}Shall we reboot?${nc}"
read response
case $response in 
	y|Y|YES|yes|Yes)
		sudo reboot
esac
exit
